### ISSUE TITLE
Issues with documentation

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/comments_mapping#2]
I get stuck at the first step
<img width="1348" alt="Capture d’écran 2021-06-23 à 17 17 57" src="https://user-images.githubusercontent.com/11473995/123123275-01a09600-d447-11eb-9663-95e197a9a693.png">

**Comment by armandfardeau** [comment]
Hi @virgile-dev could you try to run `make start` command?

**Comment by virgile-dev** [comment]
Ok ! I've used `make start` I can now run the commands in the Readme. 
Now it's context and instructions I'm lacking : 
- where should I put the files I want to be mapped
- where do I go check out the results of the mapping

**Comment by armandfardeau** [comment]
Basically this takes docs from ./test_data, transforms it and outputs the content to ./dist

You should be able to modify the content of ./test_data to use it.
We are going to work on a better documentation.
